GreycLab/CImg

- CImg.h
Dear dtschump,
I had faced with small problem of catching the CImgException.
I by mistake, caught it without reference and it produced double free of allocated memory.
I created a small fix for it and hope that it would be helpful.
Thanks,
m0stik
> Fixed bug: Shallow copy of CImgException

- examples/Makefile
On MinGW, `make Mwindows` produces executables without .exe suffix. Makefile did not provide an option to set the suffix of executables.
```
$ make CC=i686-w64-mingw32.static-gcc EXESFX=.exe ...
```
See also https://github.com/mxe/mxe/pull/877
> examples Makefile: add option exe suffix (EXESFX)

- examples/Makefile
Changes of INCDIR (-I) and DEFINE (-D, -m, -f) are now independent.
It is convenient for cross-compilation with MinGW.
See also https://github.com/mxe/mxe/pull/877
> examples Makefile: split CFLAGS to DEFINE, INCDIR

- html/CImg_documentation.h
Just read the introduction page and found some minor grammatical errors. 
The sentence under "What's next ?" should probably be rephrased as well but I'm not sure how, so I'll let someone else handle that.
> fix minor grammatical errors in the overview page

- CImg.h
I'm not quite sure if there's some plugin or feature that needs the full version, but I didn't encounter anything (but I would argue that if there some extra stuff needed it should be included manually).
The reason for this is that when we used CImg together with boost asio there was some conflict with CImg pulling in winsock.
> use minimal Windows include

- CImg.h
Thought these changes were reasonable.
The test around the #defines stops warning that say the #defines are already defined.
The 8 byte swap handles doubles and other 64 bit byte swaps well compared to the default method
> added checks for #define definitions.  added a 8 byte byte swap

- CImg.h
This PR fixes a couple bugs that I ran in to:
- Inability to call external programs with spaces in their paths
- Inability to call any external programs when building in unicode mode on Windows
**Changes I made:**
- Explicitly use ASCII characters in cimg::system().  Before, it was casting the ASCII string (char*) to a Unicode string (TCHAR*), which was creating corrupt data that CreateProcess couldn't parse.
- Remove the std::system() call that was set up as a backup if CreateProcess failed.  As it turns out, std::system() on Windows has some [totally bananas quoting rules](https://stackoverflow.com/questions/9964865/c-system-not-working-when-there-are-spaces-in-two-different-parameters) that make it not able to correctly execute commands in the regular string format.  Now that the …
> Fix CreateProcess call, add quoting for executable paths on system calls

- CImg.h
- examples/CMakeLists.txt
Hello!
I've added support for heic files via libheif -> https://github.com/strukturag/libheif
I wanted to implement this because of this project
https://gitlab.com/opennota/phash
which is used by this project
https://gitlab.com/opennota/findimagedupes
I've tested this using the example `tutorial` program.
I tried to follow some of the style but I do find it hard to read. If you are interested in this PR just let me know what I can do to improve the formatting.
I'm also not 100% sure I've implemented this correctly
```
CImg<uint8_t> buffer(data, width, height, depth, spectrum);
assign(width, height, depth, spectrum);
```
From what I gather the constructor will create a new buffer and copy the data into it (it's hard for me to read the templates). Then the `assign` makes sure `this` has the …
> add heic and avif support via libheif

- examples/Makefile
loongarch64 is a new architecture, currently there is only one cpu, so delete -mtune option
> delete -mtune option on loongarch architecture

- examples/Makefile
The commit being fixed is completely pointless, as it was introducing C
preprocessor directives into a Makefile. That aside, there certainly are
some GCC ports that does not have support for `-mtune=generic`, so probe
for support dynamically instead.
Fixes: f1996f1 ("delete -mtune option on loongarch architecture")
P.S. I came across that PR just by coincidence, I haven't looked at properly testing the library yet. Do exercise caution if you're going to directly merge this; I will try to verify the changes on actual LoongArch hardware in a day or so.
> examples: probe for -mtune=generic support, fix wrong LoongArch support

- CImg.h
Hi
The CeCILL license says to share any modifications made with the community. I added this line to stop it complaining when I wanted to load in some png files that were presumably interlaced. Do with this as you wish.
> Set PNG interlacing on to avoid an error message

- CImg.h
This pull request seeks to harden CImg against RAM exhaustions. ``cimg_max_file_size`` has been renamend to ``cimg_max_buf_size`` and a check was implemented inside ``safe_size`` to prevent sizes that are too large. This gives the user of the lib more control over possible resource consumption. Everywhere ``safe_size`` is used, cimg now checks if this size is within the user specified limits.
> add global hardening against RAM exhaustions in safe_size

- CImg.h
Hey @dtschump,
This PR enables using MSVC's OpenMP support. All it took was a slight adjustment to the flag type, as VC doesn't support atomic booleans (yet; I'll make sure to report it after this). I also took the chance to fix the macro used to inline the directive.
> Support MSVC's OpenMP 2.0

- CImg.h
The `draw_text` version accepting the font size in it's documentation stated other sizes for perfect matches than what is defined in `font_height`.
> Wrong font size doc

- CImg.h
small fix for  `cimg_no_system_calls`
example for iOS 
I can't build  with `-Werror`
```
#ifdef __APPLE__
#include <TargetConditionals.h>
#ifdef TARGET_OS_IPHONE
// iOS, tvOS, or watchOS device
#define cimg_no_system_calls
#endif
#endif
#include <CImg.h>
```
```
error: unused parameter 'command' [-Werror,-Wunused-parameter]
error: unused parameter 'is_verbose' [-Werror,-Wunused-parameter]
```
> fix for cimg_no_system_calls

- CImg.h
- On unix-like systems, use stat to check if the path is a file, this is more clear and faster than using fopen
- use is_file instead of access, which is more portable and can give us correct results under a setuid/setgid program (access only uses the real UID and real GID sometime can run into problems)
> Improve is_file and posix_searchpath

- plugins/jpeg_buffer.h
Hello,
The only change follows what I described in my comment under the issue. To summarize, for 32 bit it is possible to purposefully tamper with certain jpg header fields leading to the size of a heap allocation to be miscalculated due to integer overflow. 
All this change does is use the existing `CImg::safe_size()` to throw an exception in case the calculations performed using the relevant `cinfo` fields lead to an integer overflow. This will consequentially prevent the crash I was able to produce from happening with the provided `use_jpeg_buffer.cpp` example, and the possibility for heap corruption caused by out of bounds memory access.
Thanks!
> Addresses issue #415

- CImg.h
Using `CImg<T>` instead of `std::vector<T>`.
> Remove the usage of std::vector

- CImg.h
The STL declares `std::min` and `std::max` functions in the "algorithm" header.
Some libraries such as libmagick++ has already included "algorithm", that's why the code can be compiled if we use these libraries or build project with cmake. However, if we don't use these libraries and use the `cing::min/max` functions (or other functions use cimg::min/max) , then we will encounter compiler errors.
So add algorithm back.
P.S. Another option is to define cimg's own two-argument version of the min and max functions. But this violates the DRY principle.
> Fix compiler errors

- CImg.h
Changes:
- add `path_exists` to check a path whether exists
- use `path_exists` and `is_file` instead fopen to check a path or file whether exists
Why:
- open then close a file is significantly slow
- fopen requires an additional file descriptor to be consumed, which can lead to "too many open files" error
- make the code more readable
- use `path_exists` and `is_file` reduce binary file size from 1139624 bytes to 1109248 bytes, reduced ~30KiB on Linux
`path_exists` use win_getfileattributes on Windows, faccessat on POSIX and std_fopen on `cimg_OS==0`. It checks both directories and files.
> Simplify file existence checks

- examples/CMakeLists.txt
- examples/gaussian_fit1d.cpp
Also fix a c++ variable liftime issue in the example code:
> Fix examples building for CMake 4.0

- CImg.h
They change the function back in v1.20.2, it's crazy.
> Fix for libheif v1.20.2
